import { NextRequest, NextResponse } from "next/server"
import { SarvamAIClient } from "sarvamai"

const client = new SarvamAIClient({
  apiSubscriptionKey: process.env.SARVAM_API_KEY,
})

export async function POST(req: NextRequest) {
  try {
    const { text, language } = await req.json()

    if (!text) {
      return NextResponse.json({ error: "Missing text" }, { status: 400 })
    }

    const response = await client.textToSpeech.convert({
      text: text,
      target_language_code: language || "hi-IN",
    })

    const base64Audio = response.audios?.[0]

    if (!base64Audio) {
      throw new Error("No audio generated by the model")
    }

    return NextResponse.json({ audio: base64Audio })
  } catch (error: any) {
    console.error("TTS error:", error)
    return NextResponse.json(
      { error: error.message || "Something went wrong" },
      { status: 500 }
    )
  }
}
