import { NextRequest, NextResponse } from "next/server"
import { SarvamAIClient } from "sarvamai"

import { toUserMessage } from "@/lib/errors"

const client = new SarvamAIClient({
  apiSubscriptionKey: process.env.SARVAM_API_KEY,
})

type TtsTargetLanguage = NonNullable<
  Parameters<typeof client.textToSpeech.convert>[0]["target_language_code"]
>

const ALLOWED_TARGET_LANGUAGES = new Set<TtsTargetLanguage>([
  "hi-IN",
  "mr-IN",
  "gu-IN",
  "ta-IN",
  "te-IN",
  "kn-IN",
  "bn-IN",
  "pa-IN",
])

function resolveTargetLanguage(input: string): TtsTargetLanguage {
  return ALLOWED_TARGET_LANGUAGES.has(input as TtsTargetLanguage)
    ? (input as TtsTargetLanguage)
    : "hi-IN"
}

export async function POST(req: NextRequest) {
  try {
    const { text, language } = await req.json()

    if (!text) {
      return NextResponse.json({ error: "Missing text" }, { status: 400 })
    }

    const targetLanguage =
      typeof language === "string" ? resolveTargetLanguage(language) : "hi-IN"

    const response = await client.textToSpeech.convert({
      text: text,
      target_language_code: targetLanguage,
    })

    const base64Audio = response.audios?.[0]

    if (!base64Audio) {
      throw new Error("No audio generated by the model")
    }

    return NextResponse.json({ audio: base64Audio })
  } catch (error: any) {
    console.error("TTS error:", error)
    const msg = toUserMessage(error, {
      fallbackTitle: "Couldn’t generate audio right now",
      fallbackDescription: "Please try again in a moment.",
      context: "api.speeches",
      status: 500,
    })
    return NextResponse.json(
      { error: msg.title, description: msg.description, code: msg.code },
      { status: 500 }
    )
  }
}
